# Generated by Django 2.2.14 on 2021-09-23 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
